// Schema generation — the equivalent of `@better-auth/cli generate`, but using
// better-auth's OWN internal `getSchema()` so there is zero version drift
// between the schema and the runtime (the external CLI tops out at 1.4.21 while
// the runtime is 1.6.13). This is the SAME function the CLI consumes.
//
// Output 1: spike-ddl.sql      — SQLite CREATE TABLE statements (applied by migrate.ts)
// Output 2: schema.ts          — Drizzle table objects the adapter maps onto
//
// We rebuild the plugin set here (without the Drizzle adapter, which is the
// thing that needs the schema) so this can run before schema.ts exists.
import { getSchema } from "better-auth/db";
import { siwe } from "better-auth/plugins/siwe";
import { jwt } from "better-auth/plugins/jwt";
import { organization } from "better-auth/plugins/organization";
import type { BetterAuthOptions } from "better-auth";
import { writeFileSync } from "node:fs";

const options: BetterAuthOptions = {
  user: {
    additionalFields: {
      activeWorld: { type: "string", required: false, input: true },
    },
  },
  plugins: [
    siwe({ domain: "localhost", getNonce: async () => "x", verifyMessage: async () => true }),
    jwt(),
    organization(),
  ],
};

const tables = getSchema(options);

// ---- SQLite type mapping ----
function sqliteType(t: string): string {
  if (t === "number") return "INTEGER";
  if (t === "boolean") return "INTEGER"; // 0/1
  // Dates: the Drizzle column uses integer({mode:"timestamp"}) -> epoch seconds
  // stored as INTEGER. Match that here so DDL affinity == Drizzle write mode.
  if (t === "date") return "INTEGER";
  if (t === "json" || (Array.isArray(t) === false && String(t).endsWith("[]"))) return "TEXT";
  return "TEXT"; // string and everything else
}

// ---- Drizzle column mapping (better-sqlite3 dialect) ----
function drizzleCol(name: string, t: string, attr: any): string {
  const col = `"${name}"`;
  let base: string;
  if (t === "number") base = `integer(${col})`;
  else if (t === "boolean") base = `integer(${col}, { mode: "boolean" })`;
  else if (t === "date") base = `integer(${col}, { mode: "timestamp" })`;
  else base = `text(${col})`;
  if (name === "id") base += `.primaryKey()`;
  if (attr.required !== false && name !== "id") base += `.notNull()`;
  if (attr.unique) base += `.unique()`;
  return base;
}

const sortedTables = Object.entries(tables).sort((a, b) => (a[1].order ?? 0) - (b[1].order ?? 0));

let ddl = "-- generated by gen-schema.ts via better-auth getSchema()\nPRAGMA foreign_keys=ON;\n\n";
let drizzle = `// generated by gen-schema.ts — DO NOT EDIT BY HAND\nimport { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";\n\n`;

const tableNames: string[] = [];
for (const [tableName, def] of sortedTables) {
  tableNames.push(tableName);
  const cols: string[] = [];
  const ddlCols: string[] = [];
  const fks: string[] = [];

  // id column (better-auth always uses string id "id")
  ddlCols.push(`  "id" TEXT PRIMARY KEY NOT NULL`);
  cols.push(`  id: text("id").primaryKey()`);

  for (const [fieldName, attrRaw] of Object.entries(def.fields)) {
    const attr = attrRaw as any;
    if (fieldName === "id") continue;
    const t = attr.type as string;
    let line = `  "${fieldName}" ${sqliteType(t)}`;
    if (attr.required !== false) line += " NOT NULL";
    if (attr.unique) line += " UNIQUE";
    if (attr.references) {
      fks.push(
        `  FOREIGN KEY ("${fieldName}") REFERENCES "${attr.references.model}"("${attr.references.field}") ON DELETE ${(attr.references.onDelete ?? "cascade")}`,
      );
    }
    ddlCols.push(line);
    cols.push(`  ${JSON.stringify(fieldName)}: ${drizzleCol(fieldName, t, attr)}`);
  }

  ddl += `CREATE TABLE IF NOT EXISTS "${tableName}" (\n${[...ddlCols, ...fks].join(",\n")}\n);\n\n`;
  drizzle += `export const ${tableName} = sqliteTable(${JSON.stringify(tableName)}, {\n${cols.join(",\n")},\n});\n\n`;
}

writeFileSync("./spike-ddl.sql", ddl);
writeFileSync("./schema.ts", drizzle);

console.log("Generated tables (in dependency order):", tableNames.join(", "));
console.log("Wrote ./spike-ddl.sql and ./schema.ts");
