// generated by gen-schema.ts — DO NOT EDIT BY HAND
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  "name": text("name").notNull(),
  "email": text("email").notNull().unique(),
  "emailVerified": integer("emailVerified", { mode: "boolean" }).notNull(),
  "image": text("image"),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "updatedAt": integer("updatedAt", { mode: "timestamp" }).notNull(),
  "activeWorld": text("activeWorld"),
});

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  "expiresAt": integer("expiresAt", { mode: "timestamp" }).notNull(),
  "token": text("token").notNull().unique(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "updatedAt": integer("updatedAt", { mode: "timestamp" }).notNull(),
  "ipAddress": text("ipAddress"),
  "userAgent": text("userAgent"),
  "userId": text("userId").notNull(),
  "activeOrganizationId": text("activeOrganizationId"),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  "accountId": text("accountId").notNull(),
  "providerId": text("providerId").notNull(),
  "userId": text("userId").notNull(),
  "accessToken": text("accessToken"),
  "refreshToken": text("refreshToken"),
  "idToken": text("idToken"),
  "accessTokenExpiresAt": integer("accessTokenExpiresAt", { mode: "timestamp" }),
  "refreshTokenExpiresAt": integer("refreshTokenExpiresAt", { mode: "timestamp" }),
  "scope": text("scope"),
  "password": text("password"),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "updatedAt": integer("updatedAt", { mode: "timestamp" }).notNull(),
});

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  "identifier": text("identifier").notNull(),
  "value": text("value").notNull(),
  "expiresAt": integer("expiresAt", { mode: "timestamp" }).notNull(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "updatedAt": integer("updatedAt", { mode: "timestamp" }).notNull(),
});

export const walletAddress = sqliteTable("walletAddress", {
  id: text("id").primaryKey(),
  "userId": text("userId").notNull(),
  "address": text("address").notNull(),
  "chainId": integer("chainId").notNull(),
  "isPrimary": integer("isPrimary", { mode: "boolean" }).notNull(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
});

export const jwks = sqliteTable("jwks", {
  id: text("id").primaryKey(),
  "publicKey": text("publicKey").notNull(),
  "privateKey": text("privateKey").notNull(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "expiresAt": integer("expiresAt", { mode: "timestamp" }),
});

export const organization = sqliteTable("organization", {
  id: text("id").primaryKey(),
  "name": text("name").notNull(),
  "slug": text("slug").notNull().unique(),
  "logo": text("logo"),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "metadata": text("metadata"),
});

export const member = sqliteTable("member", {
  id: text("id").primaryKey(),
  "organizationId": text("organizationId").notNull(),
  "userId": text("userId").notNull(),
  "role": text("role").notNull(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
});

export const invitation = sqliteTable("invitation", {
  id: text("id").primaryKey(),
  "organizationId": text("organizationId").notNull(),
  "email": text("email").notNull(),
  "role": text("role"),
  "status": text("status").notNull(),
  "expiresAt": integer("expiresAt", { mode: "timestamp" }).notNull(),
  "createdAt": integer("createdAt", { mode: "timestamp" }).notNull(),
  "inviterId": text("inviterId").notNull(),
});

